### ISSUE TITLE
Debugger asking for runtime executable

### ISSUE THREAD

**Issue by ziul123** [arthwang/vsc-prolog#6]
When I try to use the debugger it says: 
"Cannot debug the prolog file. The Prolog executable '/usr/bin/swipl' was not found. Correct 'runtimeExecutable' setting in launch.json file."
What file should I put there? Is it the same as the linter one?
Thank you for the help.

**Comment by arthwang** [comment]
Yeah, it's the same as the one for the linter.  We need to set the path since the debug adpter is a standalone program and can't access vscode settings.  The document says:  _These debug extensions differ from other extensions in that their implementation is not running in the extension host, but as a separate standalone program, a so-called debug adapter._

**Comment by ziul123** [comment]
Will do. Thank you for the help.

**Comment by ziul123** [comment]
Sorry for closing and then reopening the issue but it still gives an error. It says:
"Unable to open 'test.pl': File not found (file:///users/user%20name/desktop/prolog%20programs/test.pl)."
It seems it is not recognizing the file, however I have not changed the "program" setting in launch.json.
Do you know what could be the problem? Should I put the program somewhere other than my desktop?
Thank you.

**Comment by arthwang** [comment]
It seems that it's a bug of the vscode debug package that doesn't unescape properly the source file path containing spaces.  As a workaround would you please not contain spaces in your source file path.

**Comment by ziul123** [comment]
Not a problem. Thanks again and sorry for the bother!
